In [1]:
import torch

In [2]:
a = torch.tensor([1.], requires_grad=True)

In [3]:
x1 = 2
y1 = 5
yp1 = x1 * a
loss1 = (yp1 - y1)**2

In [4]:
loss1.backward()
print(a.grad)  # 2 * (1 * 2 - 5) * 2 = -12

tensor([-12.])


In [5]:
a.grad = None  # clear grad

In [6]:
x2 = 6
y2 = 5
yp2 = x2 * a
loss2 = (yp2 - y2)**2

In [7]:
loss2.backward()
print(a.grad)  # 2 * (1 * 6 - 5) * 6 = 12

tensor([12.])


In [8]:
a.grad = None  # clear grad

In [9]:
x1 = 2
y1 = 5
yp1 = x1 * a
loss1 = (yp1 - y1)**2
x2 = 6
y2 = 5
yp2 = x2 * a
loss2 = (yp2 - y2)**2
loss = loss1 + loss2

In [10]:
loss.backward()
print(a.grad)  # (-12) + 12 = 0

tensor([0.])
