In [1]:
import argparse
import numpy as np
import pandas as pd
from dgutils.pandas import add_columns
from utils import PredictorSPlitModel, arr2db, EvalMetric

/Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/tqdm/autonotebook/__init__.py:14: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  " (e.g. in jupyter console)", TqdmExperimentalWarning)
Using TensorFlow backend.
/Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py:32: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  from tensorflow.python.framework import fast_tensor_util
/Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  from . import _csparsetools
/Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:182: RuntimeWarning: numpy.ufu

In [2]:
model = PredictorSPlitModel('model/2019_09_12.1/model.hdf5')

W0918 18:34:58.224569 4730213824 deprecation_wrapper.py:119] From /Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0918 18:34:58.315700 4730213824 deprecation_wrapper.py:119] From /Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:131: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0918 18:34:58.317370 4730213824 deprecation_wrapper.py:119] From /Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0918 18:34:58.407588 4730213824 deprecation_wrapper.py:119] From /Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:

4


/Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/keras/engine/saving.py:251: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if weight_names:
W0918 18:35:00.903639 4730213824 deprecation_wrapper.py:119] From /Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0918 18:35:01.379962 4730213824 deprecation.py:323] From /Users/alicegao/anaconda2/envs/dg_work_py2/lib/python2.7/site-packages/tensorflow/python/ops/math_grad.py:1250: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0918 18:35:06.211664 4730213824 utils.py:269] Model missing names layers, w

In [3]:
seq = 'ACGCGUCGCGU'

In [4]:
y = model.predict_one_step_ar(seq)

100%|██████████| 10/10 [00:00<00:00, 26.37it/s]


In [5]:
y[0][0, :, :, 0]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
i_idxes = np.arange(0, 10 - 2)
j_idxes = np.arange(2, 10)

vals_sampled = np.asarray([0, 1, 0, 1, 0, 0, 1, 0])


In [8]:
slice_one_row = i_idxes[np.where(vals_sampled == 1)]
slice_one_col = j_idxes[np.where(vals_sampled == 1)]
slice_one_dup = np.intersect1d(slice_one_row, slice_one_col)

In [9]:
print i_idxes
print j_idxes

[0 1 2 3 4 5 6 7]
[2 3 4 5 6 7 8 9]


In [10]:
slice_one_row

array([1, 3, 6])

In [11]:
slice_one_col

array([3, 5, 8])

In [12]:
slice_one_dup

array([3])

In [13]:
for a in slice_one_dup:
    print np.where(i_idxes == a)
    print np.where(j_idxes == a)
#     print i_idxes.argwhere(a)
#     print j_idxes.argwhere(a)

(array([3]),)
(array([1]),)


In [14]:
vals_sampled[np.where(i_idxes == a)] = 0

In [15]:
np.where(i_idxes == a)[0][0]

3

In [16]:
np.where((i_idxes == a) | (j_idxes == a))

(array([1, 3]),)

In [17]:
i_idxes[[]]

array([], dtype=int64)